### ISSUE TITLE
What is ActivityMainBinding?

### ISSUE THREAD

**Issue by Jun711** [ahmedrizwan/RxRealmRetroKotlin#1]
Hi Ahmed, 

Thank you for making this kotlin tutorial. I wonder what the following import is. 
Thank you!

import com.minimize.android.rxretrorealm.databinding.ActivityMainBinding

**Comment by ahmedrizwan** [comment]
Hi Jun711! 

ActivityMainBinding is a [Databinding](https://developer.android.com/topic/libraries/data-binding/index.html) generated class for _activity_main.xml_ 
Using Databinding is totally optional, rather I would suggest not using it with Kotlin as it sometimes causes compilation issues. 
In short, you can skip the Databinding part. Simple _findViewById_ or [Kotlin Android Extensions](https://kotlinlang.org/docs/tutorials/android-plugin.html) works just as fine. 

Thanks!

**Comment by Jun711** [comment]
I see. Thanks. Just wonder how to do the generation of ActivityMainBinding class?
I am pretty new to Android. thank you!

There is another import:
import android.databinding.DataBindingUtil
Are they different?
